spring:
  application:
    name: project-cloud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB      # ?? 1?? ?? ??
      max-request-size: 10MB   # ? ?? HTTP ??? ?? ? ?? ?? ??



server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health