spring:
  config:
    import: "aws-parameterstore:/cloud-project-app/prod/"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true
logging:
  level:
    root: INFO

